
# .github/recent-activity.config.yml

# Your GitHub username
username: DuvRoman

# The maximum number of events to show
max: 5

# A list of repositories to exclude
exclude:
  - my-private-repo

name: Update README2

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4.2.2
      
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
